# Generated by Django 2.1.2 on 2018-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('ID', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=50)),
                ('Contact_No', models.BigIntegerField(null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('Department', models.CharField(max_length=100)),
            ],
        ),
    ]
