# Generated by Django 2.1.2 on 2018-11-19 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('Reg_No', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('Last_name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=50)),
                ('Patient_Age', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('Contact_No', models.BigIntegerField()),
                ('Patient_Address', models.TextField(max_length=100)),
                ('highlight', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.TextField(max_length=300)),
                ('Prescription', models.TextField(max_length=200)),
                ('Remarks', models.TextField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='Date prescribed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ('patient',),
            },
        ),
    ]
